# Generated by Django 4.2.9 on 2025-03-27 14:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('name', models.CharField(max_length=255, verbose_name='Tên lớp')),
                ('academic_year', models.CharField(blank=True, max_length=25, null=True, verbose_name='Năm học')),
                ('class_size', models.SmallIntegerField(default=30, verbose_name='Sĩ số')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'classroom',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài kiểm tra')),
                ('room_name', models.CharField(max_length=255, verbose_name='Tên phòng thi')),
                ('room_code', models.CharField(max_length=15, unique=True, verbose_name='Mã phòng thi')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('finish_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('time_todo', models.IntegerField(default=15, verbose_name='Thời gian làm bài (phút)')),
                ('retry', models.SmallIntegerField(default=1, verbose_name='Số lượt thi tối đa')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.classroom', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Bài kiểm tra',
                'verbose_name_plural': 'Bài kiểm tra',
                'db_table': 'exams',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('text', models.CharField(max_length=255, verbose_name='Câu hỏi')),
                ('answer1', models.CharField(max_length=255, verbose_name='A')),
                ('answer2', models.CharField(max_length=255, verbose_name='B')),
                ('answer3', models.CharField(max_length=255, verbose_name='C')),
                ('answer4', models.CharField(max_length=255, verbose_name='D')),
                ('correct', models.SmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=1, verbose_name='Đáp án đúng')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Câu hỏi',
                'db_table': 'choice_questions',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='QuestionFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('text', models.CharField(max_length=255, verbose_name='Câu hỏi')),
                ('answer', models.CharField(max_length=255, verbose_name='Đáp án')),
            ],
            options={
                'verbose_name': 'Câu hỏi điền',
                'verbose_name_plural': 'Câu hỏi điền',
                'db_table': 'fill_questions',
                'ordering': ['-updated_at', 'text'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('text', models.CharField(max_length=255, verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Câu hỏi (Đ/S)',
                'verbose_name_plural': 'Câu hỏi (Đ/S)',
                'db_table': 'tf_questions',
                'ordering': ['-updated_at', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('score', models.IntegerField(default=0, verbose_name='Điểm số')),
                ('is_cheat', models.BooleanField(default=False, verbose_name='Trạng thái gian lận')),
                ('is_done', models.BooleanField(default=False, verbose_name='Kiểm tra gian lận hoàn thành')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='Lý do phát hiện gian lận')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.exam', verbose_name='Bài thi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Kết quả thi',
                'verbose_name_plural': 'Kết quả thi',
                'db_table': 'results',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('name', models.CharField(max_length=255, verbose_name='Tên môn học')),
                ('teaching_hour', models.SmallIntegerField(default=18, verbose_name='Số tiết giảng dạy')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'subjects',
                'ordering': ['-updated_at', 'name', '-teaching_hour'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, 'Nữ'), (1, 'Nam')], null=True, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('position', models.CharField(max_length=255, verbose_name='Vị trí giảng dạy')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
                'db_table': 'teacher_profiles',
                'ordering': ['-updated_at', 'fullname'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, 'Nữ'), (1, 'Nam')], null=True, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.classroom', verbose_name='Lớp')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Học sinh',
                'db_table': 'student_profiles',
                'ordering': ['-updated_at', 'fullname'],
            },
        ),
        migrations.CreateModel(
            name='ResultTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('answer', models.CharField(default='', max_length=7, verbose_name='Đáp án chọn')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questiontruefalse', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Kết quả đúng sai',
                'verbose_name_plural': 'Kết quả đúng sai',
                'db_table': 'result_tf',
            },
        ),
        migrations.CreateModel(
            name='ResultFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu trả lời')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questionfill', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Kết quả điền',
                'verbose_name_plural': 'Kết quả điền',
                'db_table': 'result_fill',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('is_cheat', models.BooleanField(default=False, verbose_name='Trạng thái gian lận')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='Lý do phát hiện gian lận')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.exam')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video giám sát',
                'verbose_name_plural': 'Video giám sát',
                'db_table': 'monitors',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.teacherprofile', verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='exam',
            name='part_1',
            field=models.ManyToManyField(to='quiz.question', verbose_name='Phần I'),
        ),
        migrations.AddField(
            model_name='exam',
            name='part_2',
            field=models.ManyToManyField(to='quiz.questiontruefalse', verbose_name=''),
        ),
        migrations.AddField(
            model_name='exam',
            name='part_3',
            field=models.ManyToManyField(to='quiz.questionfill', verbose_name='Phần III'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.subject', verbose_name=''),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.teacherprofile', verbose_name='Giáo viên chủ nhiệm'),
        ),
        migrations.CreateModel(
            name='AnswerTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời điểm cập nhật')),
                ('clause', models.CharField(max_length=255, verbose_name='Mệnh đề')),
                ('answer', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=7, verbose_name='Đáp án')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questiontruefalse', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Đáp án (Đ/S)',
                'verbose_name_plural': 'Đáp án (Đ/S)',
                'db_table': 'tf_answers',
                'ordering': ['-updated_at', 'clause'],
            },
        ),
    ]
