# Generated by Django 4.2.9 on 2025-03-24 05:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('answer_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu trả lời')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Câu trả lời đúng')),
            ],
            options={
                'verbose_name': 'Đáp án',
                'verbose_name_plural': 'Đáp án',
                'db_table': 'answers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('name', models.CharField(max_length=255, verbose_name='Tên lớp')),
                ('academic_year', models.CharField(blank=True, max_length=25, null=True, verbose_name='Năm học')),
                ('class_size', models.SmallIntegerField(default=30, verbose_name='Sĩ số')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên chủ nhiệm')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài kiểm tra')),
                ('room_name', models.CharField(max_length=255, verbose_name='Tên phòng thi')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('finish_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('time_todo', models.IntegerField(default=15, verbose_name='Thời gian làm bài (phút)')),
                ('room_code', models.CharField(max_length=15, unique=True, verbose_name='Mã phòng thi')),
                ('created_by', models.CharField(max_length=255, verbose_name='Người tạo')),
                ('retry', models.SmallIntegerField(default=1, verbose_name='Số lượt thi tối đa')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.classroom', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Bài kiểm tra',
                'verbose_name_plural': 'Bài kiểm tra',
                'db_table': 'exams',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu hỏi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Câu hỏi',
                'db_table': 'questions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu hỏi')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Đáp án đúng')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Câu hỏi điền đáp án',
                'verbose_name_plural': 'Câu hỏi điền đáp án',
                'db_table': 'question_fill',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('question_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu hỏi')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Câu hỏi đúng sai',
                'verbose_name_plural': 'Câu hỏi đúng sai',
                'db_table': 'question_tf',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('score', models.IntegerField(default=0, verbose_name='Điểm số')),
                ('is_cheat', models.BooleanField(default=False, verbose_name='Trạng thái gian lận')),
                ('is_done', models.BooleanField(default=False, verbose_name='Kiểm tra gian lận hoàn thành')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='Lý do phát hiện gian lận')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.exam', verbose_name='Bài thi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Kết quả thi',
                'verbose_name_plural': 'Kết quả thi',
                'db_table': 'results',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('name', models.CharField(max_length=255, verbose_name='Tên môn học')),
                ('teaching_hour', models.SmallIntegerField(default=18, verbose_name='Số tiết giảng dạy')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, 'Nữ'), (1, 'Nam')], null=True, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('position', models.CharField(max_length=255, verbose_name='Vị trí giảng dạy')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
                'db_table': 'teacher_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, 'Nữ'), (1, 'Nam')], null=True, verbose_name='Giới tính')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.classroom', verbose_name='Lớp')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Học sinh',
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='ResultTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('answer', models.CharField(default='', max_length=7, verbose_name='Đáp án chọn')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questiontruefalse', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu trả lời')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questionfill', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Kết quả (Đ/S)')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answer', verbose_name='Đáp án lựa chọn')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question', verbose_name='Câu hỏi')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.result', verbose_name='Bài kiểm tra')),
            ],
            options={
                'verbose_name': 'Kết quả câu hỏi',
                'verbose_name_plural': 'Kết quả câu hỏi',
                'db_table': 'result_details',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('is_cheat', models.BooleanField(default=False, verbose_name='Trạng thái gian lận')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='Lý do phát hiện gian lận')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.exam')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video giám sát',
                'verbose_name_plural': 'Video giám sát',
                'db_table': 'monitors',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnswerTrueFalse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Thời điểm tạo')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm cập nhật')),
                ('clause', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mệnh đề')),
                ('answer', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='true', max_length=7, verbose_name='Đáp án')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questiontruefalse', verbose_name='Câu hỏi')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Câu hỏi'),
        ),
    ]
