# Generated by Django 4.2.9 on 2025-03-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_result_is_on_rank_alter_result_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttruefalse',
            name='clause',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mệnh đề'),
        ),
    ]
