# Generated by Django 4.2.9 on 2025-03-30 05:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_resulttruefalse_clause'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kết quả phần I', 'verbose_name_plural': 'Kết quả phần I'},
        ),
        migrations.AlterModelOptions(
            name='resultfill',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kết quả phần III', 'verbose_name_plural': 'Kết quả phần III'},
        ),
        migrations.AlterModelOptions(
            name='resulttruefalse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kết quả phần II', 'verbose_name_plural': 'Kết quả phần II'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='avt',
            field=models.ImageField(blank=True, null=True, upload_to='classroom_imgs/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='exam',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='exam_imgs/', verbose_name='Ảnh thumbnail'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avt',
            field=models.ImageField(blank=True, null=True, upload_to='student_imgs/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='subject',
            name='avt',
            field=models.ImageField(blank=True, null=True, upload_to='subject_imgs/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='avt',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_imgs/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='answertruefalse',
            name='clause',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mệnh đề'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='questionfill',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Đáp án'),
        ),
        migrations.AlterField(
            model_name='questionfill',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='questiontruefalse',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='resultfill',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Câu trả lời'),
        ),
        migrations.AlterField(
            model_name='resultfill',
            name='correct_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Đáp án đúng'),
        ),
        migrations.AlterField(
            model_name='resulttruefalse',
            name='clause',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mệnh đề'),
        ),
    ]
